---
name: Update catalogues
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        catalogue:
          - version: v5
            ref: f466c4c16e7d9f1f17d3b3f17e254e7d6cfa1d0f
          - version: current
      max-parallel: 1
    steps:
      - name: Check-out the data branch
        uses: actions/checkout@v2
        with:
          ref: data
      - name: Check-out the main repo
        uses: actions/checkout@v2
        with:
          repository: layday/instawow
          ref: ${{ matrix.catalogue.ref }}
          path: instawow
      - name: Install instawow
        run: pipx install ./instawow
      - name: Generate ${{ matrix.catalogue.version }} catalogue
        run: instawow generate-catalogue --start-date 2016-08-09
        env:
          INSTAWOW_ACCESS_TOKENS: ${{ secrets.INSTAWOW_ACCESS_TOKENS }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update ${{ matrix.catalogue.version }} catalogue
          branch: data
          file_pattern: base-catalogue-v*.json
