---
name: Update catalogues
on:
  schedule:
  - cron: 0 0 * * *
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out the data branch
      uses: actions/checkout@v2
      with:
        ref: data
    - name: Check-out the main repo
      uses: actions/checkout@v2
      with:
        repository: layday/instawow
        path: instawow
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install instawow
      run: |
        python -m pip install ./instawow
    - name: Generate the catalogues
      run: |
        python -m instawow generate-catalogue master-catalogue-v1.json
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update master catalogue
        branch: data
        file_pattern: master-catalogue-v1*.json
